# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from i2cpwm_board/PositionArray.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import i2cpwm_board.msg

class PositionArray(genpy.Message):
  _md5sum = "06b5be802f78af7b5ec929fe386952bb"
  _type = "i2cpwm_board/PositionArray"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# the PositionArray message handles multiple position assignments
# of servos.

Position[] servos

================================================================================
MSG: i2cpwm_board/Position
# the position message is used when configuring drive mode to
# assign a  servo to a specific wheel positon in the drive system
# postions are specific toe the desired drive mode
# ackerman has only one position
# 1 = drive
# differential has two positons
# 1 = left, 2 = right
# mecanum has four positions
# 1 = front left, 2 = front right, 3 = rear left, 4 = rear right
# multiple servos/motors may be used for each positon

int16 servo
int16 position
"""
  __slots__ = ['servos']
  _slot_types = ['i2cpwm_board/Position[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servos

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(PositionArray, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.servos is None:
        self.servos = []
    else:
      self.servos = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.servos)
      buff.write(_struct_I.pack(length))
      for val1 in self.servos:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.servo, _x.position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servos is None:
        self.servos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servos = []
      for i in range(0, length):
        val1 = i2cpwm_board.msg.Position()
        _x = val1
        start = end
        end += 4
        (_x.servo, _x.position,) = _get_struct_2h().unpack(str[start:end])
        self.servos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.servos)
      buff.write(_struct_I.pack(length))
      for val1 in self.servos:
        _x = val1
        buff.write(_get_struct_2h().pack(_x.servo, _x.position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.servos is None:
        self.servos = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servos = []
      for i in range(0, length):
        val1 = i2cpwm_board.msg.Position()
        _x = val1
        start = end
        end += 4
        (_x.servo, _x.position,) = _get_struct_2h().unpack(str[start:end])
        self.servos.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2h = None
def _get_struct_2h():
    global _struct_2h
    if _struct_2h is None:
        _struct_2h = struct.Struct("<2h")
    return _struct_2h
