frame_id: imu_link

rate_hz: 40.0

publish_magnetometer: true

publish_euler: true

magnetic_declination: 0.0

orientation_covariance: [2.89e-6, 0, 0, 0, 2.89e-6, 0, 0, 0, 2.89e-6]

angular_velocity_covariance: [2.89e-6, 0, 0, 0, 2.89e-6, 0, 0, 0, 2.89e-6]

linear_acceleration_covariance: [2.89e-6, 0, 0, 0, 2.89e-6, 0, 0, 0, 2.89e-6]