(cl:in-package spot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          MOTOR_POWER_STATE-VAL
          MOTOR_POWER_STATE
          SHORE_POWER_STATE-VAL
          SHORE_POWER_STATE
          LOCOMOTION_CHARGE_PERCENTAGE-VAL
          LOCOMOTION_CHARGE_PERCENTAGE
          LOCOMOTION_ESTIMATED_RUNTIME-VAL
          LOCOMOTION_ESTIMATED_RUNTIME
))