// Generated by gencpp from file spot_msgs/BehaviorFaultState.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_BEHAVIORFAULTSTATE_H
#define SPOT_MSGS_MESSAGE_BEHAVIORFAULTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <spot_msgs/BehaviorFault.h>

namespace spot_msgs
{
template <class ContainerAllocator>
struct BehaviorFaultState_
{
  typedef BehaviorFaultState_<ContainerAllocator> Type;

  BehaviorFaultState_()
    : faults()  {
    }
  BehaviorFaultState_(const ContainerAllocator& _alloc)
    : faults(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::spot_msgs::BehaviorFault_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::spot_msgs::BehaviorFault_<ContainerAllocator> >> _faults_type;
  _faults_type faults;





  typedef boost::shared_ptr< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> const> ConstPtr;

}; // struct BehaviorFaultState_

typedef ::spot_msgs::BehaviorFaultState_<std::allocator<void> > BehaviorFaultState;

typedef boost::shared_ptr< ::spot_msgs::BehaviorFaultState > BehaviorFaultStatePtr;
typedef boost::shared_ptr< ::spot_msgs::BehaviorFaultState const> BehaviorFaultStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::BehaviorFaultState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::BehaviorFaultState_<ContainerAllocator1> & lhs, const ::spot_msgs::BehaviorFaultState_<ContainerAllocator2> & rhs)
{
  return lhs.faults == rhs.faults;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::BehaviorFaultState_<ContainerAllocator1> & lhs, const ::spot_msgs::BehaviorFaultState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59543c1c1ad10a39140a97dcfc78f876";
  }

  static const char* value(const ::spot_msgs::BehaviorFaultState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59543c1c1ad10a39ULL;
  static const uint64_t static_value2 = 0x140a97dcfc78f876ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/BehaviorFaultState";
  }

  static const char* value(const ::spot_msgs::BehaviorFaultState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "BehaviorFault[] faults\n"
"\n"
"================================================================================\n"
"MSG: spot_msgs/BehaviorFault\n"
"# Cause\n"
"uint8 CAUSE_UNKNOWN = 0\n"
"uint8 CAUSE_FALL = 1\n"
"uint8 CAUSE_HARDWARE = 2\n"
"\n"
"# Status\n"
"uint8 STATUS_UNKNOWN = 0\n"
"uint8 STATUS_CLEARABLE = 1\n"
"uint8 STATUS_UNCLEARABLE = 2\n"
"\n"
"Header header\n"
"uint32 behavior_fault_id\n"
"uint8 cause\n"
"uint8 status\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::spot_msgs::BehaviorFaultState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.faults);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BehaviorFaultState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::BehaviorFaultState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::BehaviorFaultState_<ContainerAllocator>& v)
  {
    s << indent << "faults[]" << std::endl;
    for (size_t i = 0; i < v.faults.size(); ++i)
    {
      s << indent << "  faults[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::spot_msgs::BehaviorFault_<ContainerAllocator> >::stream(s, indent + "    ", v.faults[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_BEHAVIORFAULTSTATE_H
