// Generated by gencpp from file spot_msgs/EStopStateArray.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_ESTOPSTATEARRAY_H
#define SPOT_MSGS_MESSAGE_ESTOPSTATEARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <spot_msgs/EStopState.h>

namespace spot_msgs
{
template <class ContainerAllocator>
struct EStopStateArray_
{
  typedef EStopStateArray_<ContainerAllocator> Type;

  EStopStateArray_()
    : estop_states()  {
    }
  EStopStateArray_(const ContainerAllocator& _alloc)
    : estop_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::spot_msgs::EStopState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::spot_msgs::EStopState_<ContainerAllocator> >> _estop_states_type;
  _estop_states_type estop_states;





  typedef boost::shared_ptr< ::spot_msgs::EStopStateArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::EStopStateArray_<ContainerAllocator> const> ConstPtr;

}; // struct EStopStateArray_

typedef ::spot_msgs::EStopStateArray_<std::allocator<void> > EStopStateArray;

typedef boost::shared_ptr< ::spot_msgs::EStopStateArray > EStopStateArrayPtr;
typedef boost::shared_ptr< ::spot_msgs::EStopStateArray const> EStopStateArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::EStopStateArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::EStopStateArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::EStopStateArray_<ContainerAllocator1> & lhs, const ::spot_msgs::EStopStateArray_<ContainerAllocator2> & rhs)
{
  return lhs.estop_states == rhs.estop_states;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::EStopStateArray_<ContainerAllocator1> & lhs, const ::spot_msgs::EStopStateArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::EStopStateArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::EStopStateArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::EStopStateArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a14a6b761f26c00c5613f0dc614f084";
  }

  static const char* value(const ::spot_msgs::EStopStateArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a14a6b761f26c00ULL;
  static const uint64_t static_value2 = 0xc5613f0dc614f084ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/EStopStateArray";
  }

  static const char* value(const ::spot_msgs::EStopStateArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "EStopState[] estop_states\n"
"\n"
"================================================================================\n"
"MSG: spot_msgs/EStopState\n"
"# Type\n"
"uint8 TYPE_UNKNOWN = 0\n"
"uint8 TYPE_HARDWARE = 1\n"
"uint8 TYPE_SOFTWARE = 2\n"
"\n"
"# State\n"
"uint8 STATE_UNKNOWN = 0\n"
"uint8 STATE_ESTOPPED = 1\n"
"uint8 STATE_NOT_ESTOPPED = 2\n"
"\n"
"Header header\n"
"string name\n"
"uint8 type\n"
"uint8 state\n"
"string state_description\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::spot_msgs::EStopStateArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.estop_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EStopStateArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::EStopStateArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::EStopStateArray_<ContainerAllocator>& v)
  {
    s << indent << "estop_states[]" << std::endl;
    for (size_t i = 0; i < v.estop_states.size(); ++i)
    {
      s << indent << "  estop_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::spot_msgs::EStopState_<ContainerAllocator> >::stream(s, indent + "    ", v.estop_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_ESTOPSTATEARRAY_H
