// Generated by gencpp from file spot_msgs/LeaseOwner.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_LEASEOWNER_H
#define SPOT_MSGS_MESSAGE_LEASEOWNER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spot_msgs
{
template <class ContainerAllocator>
struct LeaseOwner_
{
  typedef LeaseOwner_<ContainerAllocator> Type;

  LeaseOwner_()
    : client_name()
    , user_name()  {
    }
  LeaseOwner_(const ContainerAllocator& _alloc)
    : client_name(_alloc)
    , user_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _client_name_type;
  _client_name_type client_name;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _user_name_type;
  _user_name_type user_name;





  typedef boost::shared_ptr< ::spot_msgs::LeaseOwner_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::LeaseOwner_<ContainerAllocator> const> ConstPtr;

}; // struct LeaseOwner_

typedef ::spot_msgs::LeaseOwner_<std::allocator<void> > LeaseOwner;

typedef boost::shared_ptr< ::spot_msgs::LeaseOwner > LeaseOwnerPtr;
typedef boost::shared_ptr< ::spot_msgs::LeaseOwner const> LeaseOwnerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::LeaseOwner_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::LeaseOwner_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::LeaseOwner_<ContainerAllocator1> & lhs, const ::spot_msgs::LeaseOwner_<ContainerAllocator2> & rhs)
{
  return lhs.client_name == rhs.client_name &&
    lhs.user_name == rhs.user_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::LeaseOwner_<ContainerAllocator1> & lhs, const ::spot_msgs::LeaseOwner_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::LeaseOwner_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::LeaseOwner_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::LeaseOwner_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cea27b2d1a89312b1101c1d985fe078";
  }

  static const char* value(const ::spot_msgs::LeaseOwner_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cea27b2d1a89312ULL;
  static const uint64_t static_value2 = 0xb1101c1d985fe078ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/LeaseOwner";
  }

  static const char* value(const ::spot_msgs::LeaseOwner_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string client_name\n"
"string user_name\n"
;
  }

  static const char* value(const ::spot_msgs::LeaseOwner_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.client_name);
      stream.next(m.user_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LeaseOwner_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::LeaseOwner_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::LeaseOwner_<ContainerAllocator>& v)
  {
    s << indent << "client_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.client_name);
    s << indent << "user_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.user_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_LEASEOWNER_H
