// Generated by gencpp from file spot_msgs/SystemFaultState.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_SYSTEMFAULTSTATE_H
#define SPOT_MSGS_MESSAGE_SYSTEMFAULTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <spot_msgs/SystemFault.h>
#include <spot_msgs/SystemFault.h>

namespace spot_msgs
{
template <class ContainerAllocator>
struct SystemFaultState_
{
  typedef SystemFaultState_<ContainerAllocator> Type;

  SystemFaultState_()
    : faults()
    , historical_faults()  {
    }
  SystemFaultState_(const ContainerAllocator& _alloc)
    : faults(_alloc)
    , historical_faults(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::spot_msgs::SystemFault_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::spot_msgs::SystemFault_<ContainerAllocator> >> _faults_type;
  _faults_type faults;

   typedef std::vector< ::spot_msgs::SystemFault_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::spot_msgs::SystemFault_<ContainerAllocator> >> _historical_faults_type;
  _historical_faults_type historical_faults;





  typedef boost::shared_ptr< ::spot_msgs::SystemFaultState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::SystemFaultState_<ContainerAllocator> const> ConstPtr;

}; // struct SystemFaultState_

typedef ::spot_msgs::SystemFaultState_<std::allocator<void> > SystemFaultState;

typedef boost::shared_ptr< ::spot_msgs::SystemFaultState > SystemFaultStatePtr;
typedef boost::shared_ptr< ::spot_msgs::SystemFaultState const> SystemFaultStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::SystemFaultState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::SystemFaultState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::SystemFaultState_<ContainerAllocator1> & lhs, const ::spot_msgs::SystemFaultState_<ContainerAllocator2> & rhs)
{
  return lhs.faults == rhs.faults &&
    lhs.historical_faults == rhs.historical_faults;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::SystemFaultState_<ContainerAllocator1> & lhs, const ::spot_msgs::SystemFaultState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::SystemFaultState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::SystemFaultState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::SystemFaultState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3847105c5e3204fe63ad7caa31a33575";
  }

  static const char* value(const ::spot_msgs::SystemFaultState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3847105c5e3204feULL;
  static const uint64_t static_value2 = 0x63ad7caa31a33575ULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/SystemFaultState";
  }

  static const char* value(const ::spot_msgs::SystemFaultState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SystemFault[] faults\n"
"SystemFault[] historical_faults\n"
"\n"
"================================================================================\n"
"MSG: spot_msgs/SystemFault\n"
"# Severity\n"
"uint8 SEVERITY_UNKNOWN = 0\n"
"uint8 SEVERITY_INFO = 1\n"
"uint8 SEVERITY_WARN = 2\n"
"uint8 SEVERITY_CRITICAL = 3\n"
"\n"
"Header header\n"
"string name\n"
"duration duration\n"
"int32 code\n"
"uint64 uid\n"
"string error_message\n"
"string[] attributes\n"
"uint8 severity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::spot_msgs::SystemFaultState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.faults);
      stream.next(m.historical_faults);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SystemFaultState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::SystemFaultState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::SystemFaultState_<ContainerAllocator>& v)
  {
    s << indent << "faults[]" << std::endl;
    for (size_t i = 0; i < v.faults.size(); ++i)
    {
      s << indent << "  faults[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::spot_msgs::SystemFault_<ContainerAllocator> >::stream(s, indent + "    ", v.faults[i]);
    }
    s << indent << "historical_faults[]" << std::endl;
    for (size_t i = 0; i < v.historical_faults.size(); ++i)
    {
      s << indent << "  historical_faults[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::spot_msgs::SystemFault_<ContainerAllocator> >::stream(s, indent + "    ", v.historical_faults[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_SYSTEMFAULTSTATE_H
