// Generated by gencpp from file spot_msgs/WiFiState.msg
// DO NOT EDIT!


#ifndef SPOT_MSGS_MESSAGE_WIFISTATE_H
#define SPOT_MSGS_MESSAGE_WIFISTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spot_msgs
{
template <class ContainerAllocator>
struct WiFiState_
{
  typedef WiFiState_<ContainerAllocator> Type;

  WiFiState_()
    : current_mode(0)
    , essid()  {
    }
  WiFiState_(const ContainerAllocator& _alloc)
    : current_mode(0)
    , essid(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _current_mode_type;
  _current_mode_type current_mode;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _essid_type;
  _essid_type essid;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(MODE_UNKNOWN)
  #undef MODE_UNKNOWN
#endif
#if defined(_WIN32) && defined(MODE_ACCESS_POINT)
  #undef MODE_ACCESS_POINT
#endif
#if defined(_WIN32) && defined(MODE_CLIENT)
  #undef MODE_CLIENT
#endif

  enum {
    MODE_UNKNOWN = 0u,
    MODE_ACCESS_POINT = 1u,
    MODE_CLIENT = 2u,
  };


  typedef boost::shared_ptr< ::spot_msgs::WiFiState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spot_msgs::WiFiState_<ContainerAllocator> const> ConstPtr;

}; // struct WiFiState_

typedef ::spot_msgs::WiFiState_<std::allocator<void> > WiFiState;

typedef boost::shared_ptr< ::spot_msgs::WiFiState > WiFiStatePtr;
typedef boost::shared_ptr< ::spot_msgs::WiFiState const> WiFiStateConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spot_msgs::WiFiState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spot_msgs::WiFiState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::spot_msgs::WiFiState_<ContainerAllocator1> & lhs, const ::spot_msgs::WiFiState_<ContainerAllocator2> & rhs)
{
  return lhs.current_mode == rhs.current_mode &&
    lhs.essid == rhs.essid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::spot_msgs::WiFiState_<ContainerAllocator1> & lhs, const ::spot_msgs::WiFiState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace spot_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::WiFiState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spot_msgs::WiFiState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::WiFiState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spot_msgs::WiFiState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::WiFiState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spot_msgs::WiFiState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spot_msgs::WiFiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ba66be2de3368e3a5a22e1ccf928954a";
  }

  static const char* value(const ::spot_msgs::WiFiState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xba66be2de3368e3aULL;
  static const uint64_t static_value2 = 0x5a22e1ccf928954aULL;
};

template<class ContainerAllocator>
struct DataType< ::spot_msgs::WiFiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spot_msgs/WiFiState";
  }

  static const char* value(const ::spot_msgs::WiFiState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spot_msgs::WiFiState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Mode\n"
"uint8 MODE_UNKNOWN = 0\n"
"uint8 MODE_ACCESS_POINT = 1\n"
"uint8 MODE_CLIENT = 2\n"
"\n"
"uint8 current_mode\n"
"string essid\n"
;
  }

  static const char* value(const ::spot_msgs::WiFiState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spot_msgs::WiFiState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_mode);
      stream.next(m.essid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WiFiState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spot_msgs::WiFiState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spot_msgs::WiFiState_<ContainerAllocator>& v)
  {
    s << indent << "current_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_mode);
    s << indent << "essid: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.essid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPOT_MSGS_MESSAGE_WIFISTATE_H
