// Generated by gencpp from file i2cpwm_board/IntValue.msg
// DO NOT EDIT!


#ifndef I2CPWM_BOARD_MESSAGE_INTVALUE_H
#define I2CPWM_BOARD_MESSAGE_INTVALUE_H

#include <ros/service_traits.h>


#include <i2cpwm_board/IntValueRequest.h>
#include <i2cpwm_board/IntValueResponse.h>


namespace i2cpwm_board
{

struct IntValue
{

typedef IntValueRequest Request;
typedef IntValueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct IntValue
} // namespace i2cpwm_board


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::i2cpwm_board::IntValue > {
  static const char* value()
  {
    return "0f0a503a6dfd41f41ab6b6db4044064a";
  }

  static const char* value(const ::i2cpwm_board::IntValue&) { return value(); }
};

template<>
struct DataType< ::i2cpwm_board::IntValue > {
  static const char* value()
  {
    return "i2cpwm_board/IntValue";
  }

  static const char* value(const ::i2cpwm_board::IntValue&) { return value(); }
};


// service_traits::MD5Sum< ::i2cpwm_board::IntValueRequest> should match
// service_traits::MD5Sum< ::i2cpwm_board::IntValue >
template<>
struct MD5Sum< ::i2cpwm_board::IntValueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::i2cpwm_board::IntValue >::value();
  }
  static const char* value(const ::i2cpwm_board::IntValueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::i2cpwm_board::IntValueRequest> should match
// service_traits::DataType< ::i2cpwm_board::IntValue >
template<>
struct DataType< ::i2cpwm_board::IntValueRequest>
{
  static const char* value()
  {
    return DataType< ::i2cpwm_board::IntValue >::value();
  }
  static const char* value(const ::i2cpwm_board::IntValueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::i2cpwm_board::IntValueResponse> should match
// service_traits::MD5Sum< ::i2cpwm_board::IntValue >
template<>
struct MD5Sum< ::i2cpwm_board::IntValueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::i2cpwm_board::IntValue >::value();
  }
  static const char* value(const ::i2cpwm_board::IntValueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::i2cpwm_board::IntValueResponse> should match
// service_traits::DataType< ::i2cpwm_board::IntValue >
template<>
struct DataType< ::i2cpwm_board::IntValueResponse>
{
  static const char* value()
  {
    return DataType< ::i2cpwm_board::IntValue >::value();
  }
  static const char* value(const ::i2cpwm_board::IntValueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // I2CPWM_BOARD_MESSAGE_INTVALUE_H
