// Generated by gencpp from file i2cpwm_board/StopServos.msg
// DO NOT EDIT!


#ifndef I2CPWM_BOARD_MESSAGE_STOPSERVOS_H
#define I2CPWM_BOARD_MESSAGE_STOPSERVOS_H

#include <ros/service_traits.h>


#include <i2cpwm_board/StopServosRequest.h>
#include <i2cpwm_board/StopServosResponse.h>


namespace i2cpwm_board
{

struct StopServos
{

typedef StopServosRequest Request;
typedef StopServosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StopServos
} // namespace i2cpwm_board


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::i2cpwm_board::StopServos > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::i2cpwm_board::StopServos&) { return value(); }
};

template<>
struct DataType< ::i2cpwm_board::StopServos > {
  static const char* value()
  {
    return "i2cpwm_board/StopServos";
  }

  static const char* value(const ::i2cpwm_board::StopServos&) { return value(); }
};


// service_traits::MD5Sum< ::i2cpwm_board::StopServosRequest> should match
// service_traits::MD5Sum< ::i2cpwm_board::StopServos >
template<>
struct MD5Sum< ::i2cpwm_board::StopServosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::i2cpwm_board::StopServos >::value();
  }
  static const char* value(const ::i2cpwm_board::StopServosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::i2cpwm_board::StopServosRequest> should match
// service_traits::DataType< ::i2cpwm_board::StopServos >
template<>
struct DataType< ::i2cpwm_board::StopServosRequest>
{
  static const char* value()
  {
    return DataType< ::i2cpwm_board::StopServos >::value();
  }
  static const char* value(const ::i2cpwm_board::StopServosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::i2cpwm_board::StopServosResponse> should match
// service_traits::MD5Sum< ::i2cpwm_board::StopServos >
template<>
struct MD5Sum< ::i2cpwm_board::StopServosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::i2cpwm_board::StopServos >::value();
  }
  static const char* value(const ::i2cpwm_board::StopServosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::i2cpwm_board::StopServosResponse> should match
// service_traits::DataType< ::i2cpwm_board::StopServos >
template<>
struct DataType< ::i2cpwm_board::StopServosResponse>
{
  static const char* value()
  {
    return DataType< ::i2cpwm_board::StopServos >::value();
  }
  static const char* value(const ::i2cpwm_board::StopServosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // I2CPWM_BOARD_MESSAGE_STOPSERVOS_H
